#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo sed -i "/listen 80 default_server/i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart

