#!/bin/env bash
#configures a http response to contain custom header
sudo apt-get update
sudo apt-get install nginx -y
sudo bash -c "echo 'add_header X-Served-By \$hostname;' >> /etc/nginx/nginx.conf"
sudo systemctl restart nginx
