#!/usr/bin/env bash
# Update package list
sudo apt-get update
# Install HAproxy
sudo apt-get install haproxy -y

DOMAIN_NAME="msanidi.tech"

# Configure HAproxy
echo "
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend $DOMAIN_NAME-frontend
    bind *:80
    default_backend servers

backend $DOMAIN_NAME-backend
    balance roundrobin
    server 84371-web-01 84371-web-01:80 check
    server 84371-web-02 84371-web-02:80 check
" 
[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < $CONFIG_FILE)

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
	sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
	echo 'ENABLED=1' >> $INIT_FILE
fi

if [ "$CONFIG_WORDS" -eq 0 ]; then
	echo -e "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
else
	start_tkn="#--$DOMAIN_NAME-params-begin--"
	end_tkn="#--$DOMAIN_NAME-params-end--"
	a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	a=$((a - 1))
	b=$((b + 1))
	sed -i "$a,$b"d "$CONFIG_FILE"
	echo -en "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
fi

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	service haproxy start
else
	service haproxy restart
fi

sudo service haproxy restart
