#!/bin/bash

# Update package list
sudo apt-get update

# Install HAproxy
sudo apt-get install haproxy -y

# Configure HAproxy
echo "
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    default_backend ruoya-backend

backend servers
    balance roundrobin
    server 84371-web-01 84371-web-01:80 check
    server 84371-web-02 84371-web-02:80 check
" 
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
