#!/usr/bin/env bash
#This script iterates 10 times printing "bad luck" on 4th loop, "good luck" on 8th and "Best School" for others

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
