#!/usr/bin/env bash
#Script that displays numbers from 1-20,for 4th loop iteration prints "bad luck from China", for 9th loop iteration prints "bad luck from Japan" and for 17th loop iteration prints "bad luck from Italy"

i=1

while [ $i -le 20 ]
do 
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17]
	thenecho "bad luck from Italy"
	fi
	((i++))
done
