#!/usr/bin/env bash
#fixes containers to run as nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 0.0.0.0:8080;/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache
sudo -u nginx service nginx start

