#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart

